spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event
    username: root
    password: 12345678
  data:
    redis:
      host: localhost
      port: 6379


mybatis:
  configuration:
    map-underscore-to-camel-case: true #Enable automatic conversion of camel naming and underscore naming
